services:
  dualtech:
    image: carbodrone/dualtech:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ./dualtech_logs:/dualtech_logs
      - /dev:/dev
      - /run/udev:/run/udev:ro
    privileged: true
    command: ["ros2", "launch", "carbodrone_dualtech", "main.launch.py", "use_sim_time:=false"]
    restart: on-failure
