services:
  carbodrone_px:
    image: carbodrone_px:latest
    build: carbodrone_px
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/carbodrone_px_camera:/tmp/carbodrone_px_camera
    command: ["ros2", "launch", "carbodrone_px", "real.launch.py"]
    environment:
      - ROS_DOMAIN_ID=42

  carbodrone_mars:
    image: carbodrone_mars:latest
    build: carbodrone_mars
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - /dev/shm:/dev/shm
    command: ["ros2", "run", "carbodrone_mars", "ball_detector"]
    environment:
      - ROS_DOMAIN_ID=42
